oscar_stripe/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'', TemplateView.as_view(template_name="base.html")),
    ]

oscar_stripe/forms.py
import logging
from django import forms
from django.utils.translation import ugettext_lazy as _

logger = logging.getLogger(__name__)


class ManagedAccountForm(forms.Form):
    line1 = forms.CharField(label=_("First line of address"), max_length=255)
    city = forms.CharField(label=_("City"), max_length=255)
    state = forms.CharField(label=_("State/County"), max_length=255)
    postcode = forms.CharField(
        label=_("Post/Zip-code"), max_length=64)
    last4 = forms.CharField(help_text=_("You can either provide the last 4 digits of your SSN or your entire SSN, but not both"),
                            label=_("Last 4 Digits of SSN"), max_length=4, required=False)
    ssn = forms.CharField(
        label=_("SSN"), max_length=11, required=False)
    token = forms.CharField(max_length=256, required=False, widget=forms.HiddenInput())
    supporting = forms.FileField(label=_("Supporting Document"), required=False)

    def clean(self):
        last4 = self.cleaned_data.get('last4', None)
        token = self.cleaned_data.get('token', None)
        if (last4 or token):
            if not bool(last4) ^ bool(token):
                raise forms.ValidationError(_("Please provide only one of the following: 'Last 4 Digits of SSN' or 'SSN'."))
        else:
            raise forms.ValidationError(_("Please provide either one of the following: 'Last 4 Digits of SSN' or 'SSN'."))
        return self.cleaned_data

oscar_stripe/templates/oscar_stripe/base.html
{% comment %}
As the developer of this package, don't place anything here if you can help it
since this allows developers to have interoperability between your template
structure and their own.

Example: Developer melding the 2SoD pattern to fit inside with another pattern::

    {% extends "base.html" %}
    {% load static %}

    <!-- Their site uses old school block layout -->
    {% block extra_js %}

        <!-- Your package using 2SoD block layout -->
        {% block javascript %}
            <script src="{% static 'js/ninja.js' %}" type="text/javascript"></script>
        {% endblock javascript %}

    {% endblock extra_js %}
{% endcomment %}

oscar_stripe/templates/oscar_stripe/managedaccount_confirm_delete.html
{% extends 'dashboard/layout.html' %}

{% load i18n %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'stripe:list' %}">{% trans "Managed Accounts" %}</a>
        </li>
        <li class="active">{{ title }}</li>
    </ul>
{% endblock %}

{% block headertext %}{{ title }}{% endblock %}

{% block dashboard_content %}
    <div class="table-header">
        <h2>{{ title }}</h2>
    </div>
    <form action="." method="post" class="well">
        {% csrf_token %}

        <p>{% trans "Delete Account for " %}<strong>{{ username }}</strong>{% trans " - are you sure?" %}</p>

        <div class="form-actions">
            <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
            {% trans "or" %}
            <a href="{% url 'stripe:list' %}">{% trans "cancel" %}</a>
        </div>
    </form>
{% endblock %}

oscar_stripe/templates/oscar_stripe/managedaccount_detail.html
{% extends 'dashboard/layout.html' %}
{% load i18n %}
{% load render_table from django_tables2 %}
{% load stylists_extra %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'stripe:list' %}">{% trans "Managed Accounts" %}</a>
        </li>
        <li class="active">{{ title }}</li>
    </ul>
{% endblock %}

{% block header %}
    <div class="page-header">
        <h1>{{ title }}</h1>
    </div>
{% endblock header %}

{% block dashboard_content %}
    <table class="table table-striped table-bordered table-hover">
        <caption>{{ title }}</caption>
        <thead>
            <tr>
                <th>{% trans "User" %}</th>
                <th>{% trans "Stripe Account ID" %}</th>
                {% block stripe_account_head %}
                    <th>{% trans "Stripe Legal Entity" %}</th>
                {% endblock stripe_account_head %}
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><a href="{% url 'dashboard:user-detail' pk=account.user.pk %}">{{ account.user.get_full_name }}</a></td>
                <td>{{ account.stripe_id }}</td>
                {% block stripe_account %}
                    <td>{{ stripe_account.legal_entity }}</td>
                {% endblock stripe_account %}
            </tr>
        </tbody>
    </table>
{% endblock dashboard_content %}

oscar_stripe/templates/oscar_stripe/managedaccount_form.html
{% extends 'dashboard/layout.html' %}
{% load i18n %}

{% block extrahead %}
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
Stripe.setPublishableKey('{{ publishable_key }}');
        var stripeResponseHandler = function(status, response) {
            var $form = $('#updateForm');

            if (response.error) {
                // Show the errors on the form
                $form.find('.payment-errors').text(response.error.message);
                $form.find('button').prop('disabled', false);
            } else {
                // need to clear ssn so we aren't sending sensitive info to server
                $form.find('button').prop('disabled', false);
                $("#id_ssn").val("");
                var token = response.id;
                $("#id_token").val(token);
                $("#updateForm").submit();
                $form.find('button').prop('disabled', true);
            }
        };
        jQuery(function($) {
            $('#updateForm').on('click', '#updateAccount', function(e) {
                $("#id_token").val("");
                var ssn = $('#id_ssn').val();
                if (ssn){
                    e.preventDefault();
                    var $form = $(this);

                    // Disable the submit button to prevent repeated clicks
                    $form.find('button').prop('disabled', true);
                    Stripe.piiData.createToken({
                        personal_id_number: ssn
                    }, stripeResponseHandler);
                    return false;
                }else{
                    return true;
                }
            });
        });
    </script>
</script>
{% endblock extrahead %}

{% block title %}
    {{ title }} | {% trans "Stylist Accounts" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'stylists:list' %}">{% trans "Stylist Accounts" %}</a>
        </li>
        <li class="active">{{ title }}</li>
    </ul>
{% endblock %}

{% block headertext %}{{ title }}{% endblock %}

{% block dashboard_content %}
    <div class="table-header">
        <h2>{{ title }}</h2>
    </div>
    <div class="well">
        <form action="" method="POST" enctype="multipart/form-data" id="updateForm">
            {% csrf_token %}
            <span class="payment-errors" style="color: red"></span>
            {% include 'partials/form_fields.html' with includes_files=1 class='wysiwyg' %}
            <div class="form-actions">
                <button id="updateAccount" class="btn btn-large btn-primary" type="submit">{% trans "Save" %}</button>
                {% trans "or" %} <a href="#" onclick="window.history.go(-1);return false" >{% trans "cancel" %}</a>.
            </div>
        </form>
    </div>
{% endblock dashboard_content %}

oscar_stripe/templates/oscar_stripe/managedaccount_list.html
{% extends 'dashboard/layout.html' %}
{% load i18n %}
{% load render_table from django_tables2 %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li class="active">{% trans "Managed Accounts" %}</li>
    </ul>
{% endblock %}

{% block header %}
    <div class="page-header">
        <h1>{{ title }}</h1>
    </div>
{% endblock header %}

{% block dashboard_content %}
    {% if accounts %}
        {% render_table accounts %}
    {% else %}
        <p>{% trans "No managed accounts found." %}</p>
    {% endif %}
{% endblock dashboard_content %}

oscar_stripe/templates/oscar_stripe/managedaccount_notes.html
{% extends 'dashboard/layout.html' %}
{% load i18n %}

{% block title %}
    {{ title }} | {% trans "Managed Accounts" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'stripe:list' %}">{% trans "Managed Accounts" %}</a>
        </li>
        <li class="active">{{ title }}</li>
    </ul>
{% endblock %}

{% block headertext %}{{ title }}{% endblock %}

{% block dashboard_content %}
    {% if notes %}
        <table class="table table-striped table-bordered table-hover">
            <caption><i class="icon-sitemap icon-large"></i>{% trans 'Notes' %}</caption>
            <thead>
                <tr>
                    <th>{% trans "User" %}</th>
                    <th>{% trans "Message" %}</th>
                    <th>{% trans "Date created" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for note in notes %}
                    <tr>
                        <td>{{ note.user }}</td>
                        <td>{{ note.message }}</td>
                        <td>{{ note.date_created }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>{% trans "There are no notes for this managed account." %}</p>
    {% endif %}
{% endblock dashboard_content %}